### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by thusser** [pyobs/pyobs-core#46]
Would be good to have so some of access control, to restrict access to modules (or even their single methods) to certain other modules. Would probably be nice to have groups as well.

**Comment by thusser** [comment]
A simple way to achieve this would be a definition of permissions in the config, like this:

```
acl:
  class: pyobs.acs.BaseACL
  rules:
    - rule: allow
      users: *
    - rule: deny
      groups: [students]
```

The `rules` would be applied one after another. So in this example, the first rule allows access to all, but then denies access to all users in the `students` group.

Another set of rules could be:

```
  rules:
    - rule: deny
      users: all
    - rule: allow
      groups: [admin]
      methods: [move_radec]
```

First, access is denied to everyone, but then users of group `admin` are permitted to call `move_radec` on this module.

So, a rule would be built from up to 4 keywords:
- `rule`: `allow` or `deny`
- `users`: either `all` or a list of usernames (optional, default is `all`)
- `groups`: list of groups (optional)
- `methods`: list of methods (optional)
